[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.0
    accessibility = 0.0
    best-practices = 0.0
    seo = 0.0
    pwa = 0.0

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[build]
  command = "npm run build"
  publish = "www"